// apps/web/src/components/VersionModal.tsx
import { ServerCrash } from 'lucide-react';

import { useStore } from '../store';
import { getGenerationConfig } from '../utils/generationConfig';
import { CornerCrosshairs } from './CornerCrosshairs';
import { EdgeLabel } from './EdgeLabel';
import { HoverScanner } from './HoverScanner';
import { TacticalModal } from './TacticalModal';
import { TacticalPanel } from './TacticalPanel';
import { TelemetryDecoration } from './TelemetryDecoration';

export function VersionModal() {
  const isVersionModalOpen = useStore((s) => s.isVersionModalOpen);
  const setIsVersionModalOpen = useStore((s) => s.setIsVersionModalOpen);
  const setManualVersion = useStore((s) => s.setManualVersion);
  const saveData = useStore((s) => s.saveData);

  if (!isVersionModalOpen) return null;

  const genConfig = saveData ? getGenerationConfig(saveData.generation) : null;
  const versions = genConfig?.versions ?? [...getGenerationConfig(1).versions, ...getGenerationConfig(2).versions];

  return (
    <TacticalModal
      isOpen={isVersionModalOpen}
      ariaLabel="Version Conflict Resolution"
      containerClassName="z-[70] items-center justify-center p-4"
      backdropClassName="bg-black/90 backdrop-blur-md"
      dialogClassName="w-full max-w-4xl border-none bg-transparent"
    >
      <TacticalPanel variant="amber" className="flex flex-col overflow-hidden border-2 sm:flex-row">
        <TelemetryDecoration
          label="SYS.ARBITRATION_MATRIX"
          className="top-0 right-4 bg-zinc-950 text-amber-500"
          dotClassName="text-amber-500 animate-pulse"
        />

        {/* Left Pane: Diagnostic Readout */}
        <div className="relative flex w-full flex-col border-amber-500/30 border-b border-dashed bg-black/60 p-6 sm:w-1/3 sm:border-r sm:border-b-0 sm:p-8">
          <EdgeLabel className="-top-2 left-4 bg-amber-950 px-2 text-amber-500">[ DIAGNOSTIC_READOUT ]</EdgeLabel>

          <div className="flex flex-1 flex-col items-center justify-center text-center">
            <div className="relative mb-6 flex h-20 w-20 items-center justify-center border border-amber-500/50 border-dashed bg-amber-500/10 shadow-[0_0_15px_rgba(245,158,11,0.2)]">
              <CornerCrosshairs className="h-2 w-2 border-amber-500" />
              <div className="absolute inset-0 scale-75 animate-[spin_3s_linear_infinite] rounded-full border border-amber-500/20 opacity-50" />
              <div className="absolute inset-0 scale-50 animate-[ping_2s_ease-out_infinite] rounded-full border border-amber-500/40" />
              <ServerCrash className="relative z-10 text-amber-500" size={32} />
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="font-black font-mono text-amber-500 text-xl uppercase tracking-tighter shadow-amber-500/20 drop-shadow-md">
                SYS.CONFLICT
              </h2>
              <div className="mt-2 border-amber-500/50 border-l-2 pl-3 text-left">
                <p className="tactical-text font-bold text-[9px] text-zinc-400 uppercase leading-relaxed">
                  [ ANOMALY ] Game version signature indistinguishable.
                </p>
                <p className="tactical-text mt-1 font-bold text-[9px] text-amber-500 uppercase leading-relaxed">
                  [ ACTION ] Manual user arbitration required to resume uplink.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Right Pane: Arbitration Matrix */}
        <div className="relative flex w-full flex-col bg-black/40 p-6 sm:w-2/3 sm:p-8">
          <EdgeLabel className="-top-2 left-4 bg-zinc-950 px-2 text-zinc-500">[ ARBITRATION_MATRIX ]</EdgeLabel>

          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
            {versions.map((v) => (
              <button
                type="button"
                key={v.id}
                aria-label={`Select ${v.label} version`}
                onClick={() => {
                  setManualVersion(v.id);
                  setIsVersionModalOpen(false);
                }}
                className="group focus-visible:tactical-focus relative flex flex-col border border-zinc-800 border-dashed bg-zinc-950 p-4 transition-all hover:scale-[1.02] hover:border-amber-500/50 hover:bg-amber-950/20 active:scale-95"
              >
                <CornerCrosshairs className="h-1.5 w-1.5 border-zinc-700 transition-colors group-hover:border-amber-500" />
                <HoverScanner colorClass="via-amber-500/20" />

                {/* Hardware node layout */}
                <div className="relative z-10 flex w-full flex-row items-center justify-between border-zinc-800 border-b border-dashed pb-3 group-hover:border-amber-500/30">
                  <div className="flex items-center gap-2">
                    <div
                      className={`h-2.5 w-2.5 border border-black shadow-lg ${v.dotColor} group-hover:animate-pulse`}
                    />
                    <span className="font-black font-mono text-[10px] text-zinc-400 uppercase tracking-[0.2em] transition-colors group-hover:text-amber-500">
                      SYS.VER
                    </span>
                  </div>
                  <span className="font-black font-mono text-[9px] text-zinc-600 uppercase transition-colors group-hover:text-amber-400">
                    [ SELECT ]
                  </span>
                </div>

                <div className="relative z-10 mt-3 flex items-center justify-center py-2">
                  <span className="font-black font-mono text-lg text-white uppercase tracking-widest drop-shadow-sm transition-colors group-hover:text-amber-400">
                    {v.label}
                  </span>
                </div>
              </button>
            ))}
          </div>
        </div>
      </TacticalPanel>
    </TacticalModal>
  );
}

// src/components/lit/version-modal.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { GameVersion } from '../../store';

// We import the config types here without bringing in React
import { getGenerationConfig } from '../../utils/generationConfig';

const AlertTriangleIcon = html`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-alert-triangle text-amber-500"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>`;

@customElement('lit-version-modal')
export class VersionModal extends LitElement {
  @property({ type: Boolean }) isOpen = false;
  @property({ type: Number }) generation = 1;
  // We can pass the versions as a JSON string to keep it strictly string-based for attribute usage,
  // or use Lit's property mapping for complex objects.
  @property({ type: Array }) versions: { id: string; label: string; dotColor: string }[] = [];

  createRenderRoot() {
    return this;
  }

  private handleVersionClick(versionId: string) {
    this.dispatchEvent(new CustomEvent('version-select', {
      detail: { versionId },
      bubbles: true,
      composed: true
    }));
  }

  render() {
    if (!this.isOpen) return null;

    // Use default versions if none provided
    const displayVersions = this.versions.length > 0
      ? this.versions
      : [...getGenerationConfig(1).versions, ...getGenerationConfig(2).versions];

    return html`
      <div class="fixed inset-0 z-[70] flex items-center justify-center p-4">
        <!-- Backdrop -->
        <div
          class="absolute inset-0 bg-black/90 backdrop-blur-md transition-opacity duration-300 animate-in fade-in"
        ></div>

        <!-- Modal Content -->
        <div
          class="relative w-full max-w-lg bg-zinc-900 rounded-[2.5rem] border border-zinc-800 p-10 space-y-8 text-center transition-all duration-300 animate-in zoom-in-95 fade-in"
        >
          <div class="space-y-2">
            <div class="inline-flex p-3 bg-amber-500/10 rounded-2xl border border-amber-500/20 mb-4">
              ${AlertTriangleIcon}
            </div>
            <h2 class="text-2xl font-display font-black uppercase tracking-tight text-white">Select Game Version</h2>
            <p class="text-xs font-bold text-zinc-500 uppercase tracking-widest leading-relaxed">We couldn't confidently detect your game version. Please select it manually.</p>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
            ${displayVersions.map(v => html`
              <button
                @click=${() => this.handleVersionClick(v.id)}
                class="group relative overflow-hidden p-6 bg-zinc-950 border border-zinc-800 rounded-3xl hover:border-red-500/50 transition-all text-center"
              >
                <div class="relative z-10 flex flex-col items-center gap-3">
                  <div class="w-3 h-3 rounded-full shadow-lg ${v.dotColor}"></div>
                  <span class="text-xs font-black uppercase tracking-[0.2em] text-zinc-100 group-hover:text-red-400 transition-colors">${v.label}</span>
                </div>
              </button>
            `)}
          </div>
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-version-modal': VersionModal;
  }
}
